import React from 'react';
import '../styles/SubmissionPackage.css';

export const SubmissionPackage = ({ certificate, content, stats }) => {
  const generateVerificationURL = () => {
    const baseURL = window.location.origin;
    return `${baseURL}?verify=${certificate.id}`;
  };

  const generateSubmissionPackage = () => {
    const submissionData = {
      content: content,
      certificate: certificate,
      verificationURL: generateVerificationURL(),
      metadata: {
        wordCount: stats.wordCount,
        charCount: stats.charCount,
        typingSpeed: stats.typingStats.averageTypingSpeed,
        timeSpent: stats.typingStats.totalTimeSpent,
        copyPasteDetected: stats.typingStats.copyPasteDetected,
        versionCount: stats.versionCount,
      },
      instructions: {
        forTeacher: "To verify this document's authenticity:",
        steps: [
          `1. Visit the verification portal: ${window.location.origin}`,
          "2. Click 'Verify Document'",
          `3. Enter Certificate ID: ${certificate.id}`,
          "4. Review the authenticity metrics",
        ],
        quickLink: `Or click this direct link: ${generateVerificationURL()}`,
      },
    };

    return submissionData;
  };

  const handleDownloadPackage = () => {
    const packageData = generateSubmissionPackage();
    const blob = new Blob([JSON.stringify(packageData, null, 2)], {
      type: 'application/json'
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `submission-package-${certificate.id}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadReadme = () => {
    const verificationURL = generateVerificationURL();
    const readmeContent = `# Document Verification Instructions

## Document Details
- Certificate ID: ${certificate.id}
- Word Count: ${stats.wordCount}
- Character Count: ${stats.charCount}
- Created: ${new Date(certificate.createdAt).toLocaleString()}

## How to Verify This Document

### Option 1: Quick Verification (Recommended)
Click this link to verify immediately:
${verificationURL}

### Option 2: Manual Verification
1. Go to: ${window.location.origin}
2. Click "Verify Document" button
3. Enter Certificate ID: ${certificate.id}
4. Click "Verify Document"

## What You'll See

The verification portal will show:
- ✓ Document authenticity status
- ✓ Typing statistics (speed, keystrokes, time spent)
- ✓ Copy/paste detection results
- ✓ Version history
- ✓ Digital signature verification
- ✓ AI content detection results

## Authenticity Metrics

- **Typing Speed**: ${Math.round(stats.typingStats.averageTypingSpeed)} words per minute
- **Total Keystrokes**: ${stats.typingStats.totalKeystrokes}
- **Time Spent**: ${Math.floor(stats.typingStats.totalTimeSpent / 60)} minutes
- **Copy/Paste Detected**: ${stats.typingStats.copyPasteDetected ? 'Yes' : 'No'}
- **Versions Saved**: ${stats.versionCount}

## Questions?

This document was created using the Verified Text Editor, which:
- Tracks keystroke patterns to ensure original authorship
- Records typing speed and behavior patterns
- Detects copy/paste operations
- Creates cryptographic signatures
- Generates verifiable certificates

---
Generated by Verified Text Editor
${new Date().toLocaleString()}
`;

    const blob = new Blob([readmeContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `VERIFICATION-INSTRUCTIONS.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyVerificationLink = () => {
    const url = generateVerificationURL();
    navigator.clipboard.writeText(url);
    alert('Verification link copied to clipboard!');
  };

  const handleEmailSubmission = () => {
    const verificationURL = generateVerificationURL();
    const subject = encodeURIComponent('Document Submission for Verification');
    const body = encodeURIComponent(`Hello,

I am submitting my document for review. Please verify its authenticity using the following information:

Certificate ID: ${certificate.id}

Quick Verification Link:
${verificationURL}

Document Statistics:
- Words: ${stats.wordCount}
- Characters: ${stats.charCount}
- Typing Speed: ${Math.round(stats.typingStats.averageTypingSpeed)} WPM
- Time Spent: ${Math.floor(stats.typingStats.totalTimeSpent / 60)} minutes
- Copy/Paste Detected: ${stats.typingStats.copyPasteDetected ? 'Yes' : 'No'}

The document content is attached separately.

Thank you!`);

    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <div className="submission-package">
      <div className="package-header">
        <h3>Submit to Teacher/Publisher</h3>
        <p>Choose how you want to submit your verified document</p>
      </div>

      <div className="verification-link-section">
        <label>Verification Link (Quick Access)</label>
        <div className="link-input-group">
          <input
            type="text"
            readOnly
            value={generateVerificationURL()}
            className="verification-url"
          />
          <button
            className="btn btn-secondary btn-sm"
            onClick={handleCopyVerificationLink}
          >
            Copy Link
          </button>
        </div>
        <p className="help-text">
          Share this link with your teacher - they can verify with one click
        </p>
      </div>

      <div className="submission-options">
        <button className="submission-btn" onClick={handleEmailSubmission}>
          <span className="btn-icon">📧</span>
          <div>
            <div className="btn-title">Email Submission</div>
            <div className="btn-description">Opens email with verification details</div>
          </div>
        </button>

        <button className="submission-btn" onClick={handleDownloadReadme}>
          <span className="btn-icon">📄</span>
          <div>
            <div className="btn-title">Download Instructions</div>
            <div className="btn-description">Get a README file with verification steps</div>
          </div>
        </button>

        <button className="submission-btn" onClick={handleDownloadPackage}>
          <span className="btn-icon">📦</span>
          <div>
            <div className="btn-title">Download Full Package</div>
            <div className="btn-description">Complete submission package (JSON)</div>
          </div>
        </button>
      </div>

      <div className="certificate-id-box">
        <label>Certificate ID</label>
        <code className="certificate-id">{certificate.id}</code>
        <p className="help-text">
          Provide this ID to your teacher for manual verification
        </p>
      </div>
    </div>
  );
};
